name: 'tiktok_ads_source'
version: '0.4.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]
models:
  tiktok_ads_source:
    +materialized: table
    +schema: stg_tiktok_ads
    tmp:
      +materialized: view
vars:
  tiktok_ads_source:
    ad_group_history: "{{ source('tiktok_ads', 'adgroup_history') }}"
    ad_history: "{{ source('tiktok_ads', 'ad_history') }}"
    campaign_history: "{{ source('tiktok_ads', 'campaign_history') }}"
    advertiser: "{{ source('tiktok_ads', 'advertiser') }}"
    ad_report_hourly: "{{ source('tiktok_ads', 'ad_report_hourly') }}"
    ad_group_hourly: "{{ source('tiktok_ads', 'adgroup_report_hourly') }}"
    campaign_report_hourly: "{{ source('tiktok_ads', 'campaign_report_hourly') }}"
  tiktok_ads__ad_group_hourly_passthrough_metrics: []
  tiktok_ads__ad_hourly_passthrough_metrics: []
  tiktok_ads__campaign_hourly_passthrough_metrics: []
