{% macro get_ad_group_history_columns() %}

{% set columns = [
    {"name": "_fivetran_synced", "datatype": dbt_utils.type_timestamp()},
    {"name": "action_days", "datatype": dbt_utils.type_numeric()},
    {"name": "adgroup_id", "datatype": dbt_utils.type_numeric()},
    {"name": "adgroup_name", "datatype": dbt_utils.type_string()},
    {"name": "advertiser_id", "datatype": dbt_utils.type_numeric()},
    {"name": "android_osv", "datatype": dbt_utils.type_string()},
    {"name": "app_download_url", "datatype": dbt_utils.type_string()},
    {"name": "app_id", "datatype": dbt_utils.type_numeric()},
    {"name": "app_name", "datatype": dbt_utils.type_string()},
    {"name": "app_type", "datatype": dbt_utils.type_string()},
    {"name": "audience_type", "datatype": dbt_utils.type_string()},
    {"name": "bid", "datatype": dbt_utils.type_float()},
    {"name": "bid_type", "datatype": dbt_utils.type_string()},
    {"name": "billing_event", "datatype": dbt_utils.type_string()},
    {"name": "budget", "datatype": dbt_utils.type_float()},
    {"name": "budget_mode", "datatype": dbt_utils.type_string()},
    {"name": "campaign_id", "datatype": dbt_utils.type_numeric()},
    {"name": "category", "datatype": dbt_utils.type_numeric()},
    {"name": "click_tracking_url", "datatype": dbt_utils.type_string()},
    {"name": "conversion_bid", "datatype": dbt_utils.type_float()},
    {"name": "cpv_video_duration", "datatype": dbt_utils.type_string()},
    {"name": "create_time", "datatype": dbt_utils.type_timestamp()},
    {"name": "creative_material_mode", "datatype": dbt_utils.type_string()},
    {"name": "dayparting", "datatype": dbt_utils.type_string()},
    {"name": "deep_bid_type", "datatype": dbt_utils.type_string()},
    {"name": "deep_cpabid", "datatype": dbt_utils.type_float()},
    {"name": "deep_external_action", "datatype": dbt_utils.type_string()},
    {"name": "display_name", "datatype": dbt_utils.type_string()},
    {"name": "enable_inventory_filter", "datatype": "boolean"},
    {"name": "external_action", "datatype": dbt_utils.type_string()},
    {"name": "fallback_type", "datatype": dbt_utils.type_string()},
    {"name": "frequency", "datatype": dbt_utils.type_numeric()},
    {"name": "frequency_schedule", "datatype": dbt_utils.type_numeric()},
    {"name": "gender", "datatype": dbt_utils.type_string()},
    {"name": "impression_tracking_url", "datatype": dbt_utils.type_string()},
    {"name": "ios_osv", "datatype": dbt_utils.type_string()},
    {"name": "is_comment_disable", "datatype": dbt_utils.type_numeric()},
    {"name": "is_hfss", "datatype": "boolean"},
    {"name": "is_new_structure", "datatype": "boolean"},
    {"name": "landing_page_url", "datatype": dbt_utils.type_string()},
    {"name": "open_url", "datatype": dbt_utils.type_string()},
    {"name": "open_url_type", "datatype": dbt_utils.type_string()},
    {"name": "opt_status", "datatype": dbt_utils.type_string()},
    {"name": "optimize_goal", "datatype": dbt_utils.type_string()},
    {"name": "pacing", "datatype": dbt_utils.type_string()},
    {"name": "package", "datatype": dbt_utils.type_string()},
    {"name": "pixel_id", "datatype": dbt_utils.type_numeric()},
    {"name": "placement_type", "datatype": dbt_utils.type_string()},
    {"name": "profile_image", "datatype": dbt_utils.type_string()},
    {"name": "schedule_end_time", "datatype": dbt_utils.type_timestamp()},
    {"name": "schedule_start_time", "datatype": dbt_utils.type_timestamp()},
    {"name": "schedule_type", "datatype": dbt_utils.type_string()},
    {"name": "skip_learning_phase", "datatype": dbt_utils.type_numeric()},
    {"name": "statistic_type", "datatype": dbt_utils.type_string()},
    {"name": "status", "datatype": dbt_utils.type_string()},
    {"name": "updated_at", "datatype": dbt_utils.type_timestamp()},
    {"name": "video_download", "datatype": dbt_utils.type_string()}
] %}

{{ return(columns) }}

{% endmacro %}